add type checks for backticks_to_code_tags
open-resources/problem_bank_helpers pull request #32
Opened 2023-11-22 05:21 UTC by yangchristina

2023-11-22 05:23 UTC, firasm requested changes
This looks like a reasonable change, but can you add a test for this particular case? 

It should fail with the old code, and pass with the new code.

2023-11-22 05:24 UTC, firasm commented
You can request a review from @Bluesy1 for the test (or if you need a hand setting it up).

2023-11-22 05:37 UTC, Bluesy1 commented
Seems like a reasonable change (xref https://ca.prairielearn.com/pl/course/38/question/270667/preview?variant_id=12765502)
A simple case should be the following dictionary I think:
```python
case = {"params": {"part1": 1, "part2": {"ans1": {1}}}
```

2023-11-22 05:54 UTC, yangchristina commented
@Bluesy1 are these tests okay? I haven't used pytest before.

2023-11-22 06:16 UTC, Bluesy1 requested changes
No need to reraise the exception - an exception getting raised already causes the test to fail. (`assert False` will just raise an AssertionError instead of whatever Exception was otherwise raised, while potentially quashing context)

Otherwise, looks good to me!

2023-11-22 06:16 UTC, Bluesy1 commented on tests/test_problem_bank_helpers_other_functionality.py
> +        assert False, f"Raised an exception {exc}"
```suggestion
    pbh.backticks_to_code_tags(data)

```

2023-11-22 06:21 UTC, Bluesy1 approved these changes
Thanks for the quick update!

I appreciate that pytest can be a bit difficult to wrap your head around at first, nice job!

2023-11-22 06:22 UTC, yangchristina commented
@Bluesy1 great, thanks for your help!

2023-12-31 16:30 UTC, firasm approved these changes

2023-12-31 16:30 UTC, merged